language: python
python: 2.7
env:
  global:
    - CC_TEST_REPORTER_ID=da3fc33536e39c833398a32ad414ecedfa3843ad78aeaa33bad851d13b52d239
install:
  - make install
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - make travis
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
