language: python
python: 2.7
env:
  global:
    - CC_TEST_REPORTER_ID=da3fc33536e39c833398a32ad414ecedfa3843ad78aeaa33bad851d13b52d239
install:
  - make install
before_script:
  - ci/travis_before_script.sh
script:
  - make lint
  - make test
  - coverage xml
after_script:
  - ci/travis_after_script.sh
