FROM python:2.7.18-stretch

WORKDIR /usr/src/app

COPY contrast_security.yaml /etc/contrast/contrast_security.yaml
COPY . .
RUN sed -i.bk "s/#'contrast/'contrast/g" pygoat/settings.py
RUN pip install contrast-agent
RUN make install
RUN python manage.py migrate
RUN python manage.py seed

CMD [ "python", "manage.py", "runserver", "0.0.0.0:8000" ]
