# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 20:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_keymanagement'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='keymanagement',
            table='"key_management"',
        ),
    ]
