# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 18:16
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(4294967295)]),
        ),
    ]
