# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 20:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170608_2002'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='keymanagement',
            table='app_key_managment',
        ),
    ]
