# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170609_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='creator_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='message',
            name='receiver_id',
            field=models.PositiveIntegerField(),
        ),
    ]
