# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 20:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170608_2003'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='keymanagement',
            table='app_key_management',
        ),
    ]
