# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 20:25
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20170608_2005'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaidTimeOff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sick_days_taken', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(4294967295)])),
                ('sick_days_earned', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(4294967295)])),
                ('pto_taken', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(4294967295)])),
                ('pto_earned', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(4294967295)])),
                ('created_at', models.DateTimeField(verbose_name='date created')),
                ('updated_at', models.DateTimeField(verbose_name='date updated')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User')),
            ],
            options={
                'db_table': 'app_paid_time_offs',
            },
        ),
        migrations.AlterModelTable(
            name='keymanagement',
            table='app_key_managements',
        ),
    ]
