# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 14:04
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20170608_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_account_num', models.CharField(max_length=255)),
                ('bank_routing_num', models.CharField(max_length=255)),
                ('percent_of_deposit', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(4294967295)])),
                ('created_at', models.DateTimeField(verbose_name='date created')),
                ('updated_at', models.DateTimeField(verbose_name='date updated')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User')),
            ],
            options={
                'db_table': 'app_pays',
            },
        ),
    ]
