# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 14:31
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_pay'),
    ]

    operations = [
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_submitted', models.DateField(verbose_name='date submitted')),
                ('score', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(4294967295)])),
                ('comments', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(verbose_name='date created')),
                ('updated_at', models.DateTimeField(verbose_name='date updated')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='r_id', to='app.User')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='u_id', to='app.User')),
            ],
            options={
                'db_table': 'app_performances',
            },
        ),
    ]
