# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 16:56
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.CharField(max_length=255)),
                ('bonuses', models.CharField(max_length=255)),
                ('years_worked', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(4294967295)])),
                ('SSN', models.CharField(max_length=255)),
                ('DoB', models.DateField(verbose_name='DoB')),
                ('created_at', models.DateTimeField(verbose_name='date created')),
                ('updated_at', models.DateTimeField(verbose_name='date updated')),
                ('encrypted_ssn', models.BinaryField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User')),
            ],
            options={
                'db_table': 'app_work_infos',
            },
        ),
    ]
