# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 17:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20170609_1425'),
        ('app', '0011_workinfo'),
    ]

    operations = [
    ]
