from app.tests.models import test_model_note
from app.tests.models import test_model_message
from app.tests.models import test_model_user
from app.tests.views import test_dashboard
from app.tests.views import test_tutorials
from app.tests.views import test_http_method
from app.tests.views import test_password_reset
from app.tests.views import test_users
from app.tests.views import test_user_benefit_forms
from app.tests.views import test_users_messages
from app.tests.views import test_users_retirement
from app.tests.views import test_tutorials
